config/routes.rb
Rails.application.routes.draw do
  match '*path' => 'bikes#index', via: ['get']
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  has_one :post, as: :postable
  accepts_nested_attributes_for :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :postable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  def index
    @bikes = Bike.all
  end

  def show
  end

  def new
    @bike = Bike.new
    @bike.build_post
  end

  def edit
  end

  def create
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render :show, status: :created, location: @bike }
      else
        format.html { render :new }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { render :show, status: :ok, location: @bike }
      else
        format.html { render :edit }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bike.destroy
    respond_to do |format|
      format.html { redirect_to bikes_url, notice: 'Bike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bike
      @bike = Bike.find(params[:id])
    end

    def bike_params
      params.require(:bike).permit(:size, :size_unit, :color, :discipline, :condition, 
                                  :brand, :model, :year, :miles, post_attributes: [:email])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/_form.html.erb
<%= form_with(model: bike, local: true) do |form| %>
  <% if bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
      <% bike.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :size_unit %>
    <%= form.text_field :size_unit %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :discipline %>
    <%= form.text_field :discipline %>
  </div>

  <div class="field">
    <%= form.label :condition %>
    <%= form.text_field :condition %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :miles %>
    <%= form.number_field :miles %>
  </div>

  <div class="field">
    <%= form.fields_for :post, @bike.post do |post| %>
      <%= post.label :email %>
      <%= post.text_field :email %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<h1>Editing Bike</h1>

<%= render 'form', bike: @bike %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>

app/views/bikes/index.html.erb
<%= react_component("BikeBinApp", props: {bikes: @bikes}) %>

<h1>This should be loading.</h1>

app/views/bikes/new.html.erb
<h1>New Bike</h1>

<%= render 'form', bike: @bike %>

<%= link_to 'Back', bikes_path %>

app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Size:</strong>
  <%= "#{@bike.size} #{@bike.size_unit}" %>
</p>

<p>
  <strong>Color:</strong>
  <%= @bike.color %>
</p>

<p>
  <strong>Type:</strong>
  <%= @bike.discipline %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @bike.condition %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @bike.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @bike.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @bike.year %>
</p>

<p>
  <strong>Miles:</strong>
  <%= @bike.miles %>
</p>

<%= link_to 'Edit', edit_bike_path(@bike) %> |
<%= link_to 'Back', bikes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikeBine</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui container content">
      <%= yield %>
    </div>
  </body>
</html>